application: pygmntr
version: 1
runtime: python
api_version: 1

handlers:

- url: /pygmentize
  script: pygmentize.py

- url: /styles
  static_dir: styles

- url: /images
  static_dir: images

- url: .*
  script: main.py
  

