pygmentize -f html -S monokai -a .syntax > monokai.css
pygmentize -f html -S monokai -a .syntax > monokai.css
pygmentize -f html -S manni -a .syntax > manni.css
pygmentize -f html -S perldoc -a .syntax > perldoc.css    
pygmentize -f html -S borland -a .syntax > borland.css      
pygmentize -f html -S colorful -a .syntax > colorful.css      
pygmentize -f html -S default -a .syntax > default.css      
pygmentize -f html -S murphy -a .syntax > murphy.css      
pygmentize -f html -S vs -a .syntax > vs.css      
pygmentize -f html -S trac -a .syntax > trac.css      
pygmentize -f html -S tango -a .syntax > tango.css      
pygmentize -f html -S fruity -a .syntax > fruity.css      
pygmentize -f html -S autumn -a .syntax > autumn.css      
pygmentize -f html -S bw -a .syntax > bw.css      
pygmentize -f html -S emacs -a .syntax > emacs.css      
pygmentize -f html -S pastie -a .syntax > pastie.css     
pygmentize -f html -S friendly -a .syntax > friendly.css      
pygmentize -f html -S native -a .syntax > native.css
